---
abstract: 'Command line interface to PSGI applications'
author:
  - 'Goro Fuji (gfx) <gfuji(at)cpan.org>'
build_requires:
  HTTP::Request::AsCGI: 0
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.0.56, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Handler-CLI
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Plack::Handler::CLI:
    file: lib/Plack/Handler/CLI.pm
    version: 0.05
recommends:
  URI::Escape::XS: 0.07
requires:
  Mouse: 0
  Plack: 0.99
  URI::Escape: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/gfx/p5-Plack-Handler-CLI/issues
  homepage: https://github.com/gfx/p5-Plack-Handler-CLI
  repository: git://github.com/gfx/p5-Plack-Handler-CLI.git
version: 0.05
x_contributors:
  - 'Fuji, Goro <g.psy.va@mail.com>'
  - 'Mario Domgoergen <mdom@taz.de>'
  - 'Fuji, Goro <gfuji@cpan.org>'
  - 'Fuji, Goro <g.psy.va@gmail.com>'
