---
abstract: 'Command line interface to PSGI applications'
author:
  - 'Goro Fuji (gfx) <gfuji(at)cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTTP::Request::AsCGI: 0
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Plack::Handler::CLI
name: Plack-Handler-CLI
no_index:
  directory:
    - example
    - inc
    - t
    - xt
recommends:
  URI::Escape::XS: 0.07
requires:
  Any::Moose: 0
  Plack: 0.99
  URI::Escape: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/p5-Plack-Handler-CLI.git
version: 0.03
